openapi: 3.0.2
info:
  title: 'Poll_test API'
  version: '1.0.0'
paths:
  /polls/vote/:
    get:
      operationId: listVotes
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vote'
          description: ''
      tags:
      - polls
    post:
      operationId: createVote
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vote'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Vote'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Vote'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vote'
          description: ''
      tags:
      - polls
  /polls/vote/user-votes/:
    get:
      operationId: userVotesVote
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vote'
          description: ''
      tags:
      - polls
  /polls/vote/{id}/:
    get:
      operationId: retrieveVote
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this vote.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vote'
          description: ''
      tags:
      - polls
    put:
      operationId: updateVote
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this vote.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vote'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Vote'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Vote'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vote'
          description: ''
      tags:
      - polls
    patch:
      operationId: partialUpdateVote
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this vote.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vote'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Vote'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Vote'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vote'
          description: ''
      tags:
      - polls
    delete:
      operationId: destroyVote
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this vote.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - polls
  /polls/:
    get:
      operationId: listPolls
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Poll'
          description: ''
      tags:
      - polls
    post:
      operationId: createPoll
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poll'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Poll'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Poll'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
      tags:
      - polls
  /polls/active/:
    get:
      operationId: activePollsPoll
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
      tags:
      - polls
  /polls/{id}/:
    get:
      operationId: retrievePoll
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this poll.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
      tags:
      - polls
    put:
      operationId: updatePoll
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this poll.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poll'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Poll'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Poll'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
      tags:
      - polls
    patch:
      operationId: partialUpdatePoll
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this poll.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poll'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Poll'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Poll'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
      tags:
      - polls
    delete:
      operationId: destroyPoll
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this poll.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - polls
components:
  schemas:
    Vote:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user_id:
          type: integer
          nullable: true
        answers:
          type: string
          nullable: true
          maxLength: 200
        poll:
          type: integer
          nullable: true
    Poll:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        questions:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              choices:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    text:
                      type: string
                      maxLength: 50
                    question:
                      type: integer
                  required:
                  - text
                  - question
              text:
                type: string
                maxLength: 50
              question_type:
                enum:
                - text field
                - choose one
                - choose many
                type: string
              poll:
                type: integer
            required:
            - choices
            - text
            - poll
        name:
          type: string
          maxLength: 50
        active:
          type: boolean
        description:
          type: string
        date_start:
          type: string
          format: date
          readOnly: true
        date_finish:
          type: string
          format: date
      required:
      - questions
      - name
      - description
      - date_finish
